### ISSUE TITLE
ERROR: parse error - invalid geometry (SQLSTATE XX000) 

### ISSUE THREAD

**Issue by tamis-laan** [cridenour/go-postgis#8]
I'm trying to execute the following:

``` go
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/cridenour/go-postgis"
	"github.com/jackc/pgx/v5"
)

func main() {
	// Establish a connection to the database
	conn, err := pgx.Connect(context.Background(), "postgres://user:password@localhost/dbname?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}

	// Ensure we have PostGIS on the database
	_, err = conn.Exec(context.Background(), "CREATE EXTENSION IF NOT EXISTS postgis")
	if err != nil {
		log.Fatal(err)
	}

	// Create the table with a PostGIS column
	_, err = conn.Exec(context.Background(), `
		CREATE TABLE IF NOT EXISTS gps_points (
			id SERIAL PRIMARY KEY,
			geom geometry(Point, 4326)
		);
	`)
	if err != nil {
		log.Fatal(err)
	}

	// Construct the PointS struct
	point := postgis.PointS{SRID: 4326, X: -84.5014, Y: 39.1064}

	// Insert the GPS point into the table
	_, err = conn.Exec(context.Background(), "INSERT INTO gps_points (geom) VALUES ($1);", point)
	if err != nil {
		log.Fatal(err)
	}

	// Retrieve the GPS point from the database
	var retrievedPoint postgis.PointS
	err = conn.QueryRow(context.Background(), "SELECT geom FROM gps_points WHERE id = $1;", 1).Scan(&retrievedPoint)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Retrieved GPS point: %+v\n", retrievedPoint)
}
```

I'm getting back the following error trying to insert the point into the database 
`ERROR: parse error - invalid geometry (SQLSTATE XX000) `.
For some reason the point is not properly converted. Any help?

**Comment by alimoli** [comment]
Same issue here, did you find a solution @tamis-laan ?

**Comment by cridenour** [comment]
From my understanding, this should be fixed now with #9 being merged.

**Comment by ainsleyclark** [comment]
I've updated to that commit but still getting an error, has anyone managed to fix this?

**Comment by yashh** [comment]
The #9 has fixed this issue but we need to use the github `@master` version. Can we cut a new release 1.0.1 please?

**Comment by cridenour** [comment]
> The [#9](https://github.com/cridenour/go-postgis/pull/9) has fixed this issue but we need to use the github `@master` version. Can we cut a new release 1.0.1 please?

Done!
